import { Subsidy } from "./types";

export const SUBSIDIES: Subsidy[] = [
  {
    id: "sii_iv",
    name: "SII 省エネ・非化石転換補助金（設備単位型）",
    org: "一般社団法人 環境共創イニシアチブ（経済産業省）",
    period: "令和7年度補正：1次 2026/3/30〜4/27 / 2次 準備中（夏想定）",
    rate: "1/3以内",
    max: "1億円（事業全体）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "省エネルギー量の要件あり。指定設備（高効率空調等）導入。補助事業ポータル登録必須",
    docs: "事業計画書・見積書・省エネ計算書・設備カタログ・登記簿等",
    url: "https://syouenehojyokin.sii.or.jp/",
    rateNum: 0.33,
    capManYen: 10000,
  },
  {
    id: "sii_gx",
    name: "SII GX設備単位型（メーカー強化枠／トップ性能枠）",
    org: "一般社団法人 環境共創イニシアチブ",
    period: "令和7年度補正：計3回公募予定（夏〜秋）",
    rate: "メーカー強化枠：上限3億円 / トップ性能枠：更新1/2・新設1/5",
    max: "3億円",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "省エネ要件 10%/1kl/1kl千万円のいずれか達成。トップランナー水準機器",
    docs: "SII事業計画書・型番リスト・省エネ計算書",
    url: "https://syouenehojyokin.sii.or.jp/",
    rateNum: 0.5,
    capManYen: 30000,
  },
  {
    id: "kanagawa",
    name: "神奈川県 中小企業省エネルギー設備導入費補助金",
    org: "神奈川県",
    period: "2026/6/1〜11/30（先着順・予算到達で終了）",
    rate: "1/3",
    max: "500万円（再エネ認定で600万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["神奈川県"],
    requirement: "CO2削減量 3t/年以上。県内事業所。エアコン・LED・ボイラー等が対象",
    docs: "事業計画書・省エネ計算書・見積書・現況写真",
    url: "https://www.pref.kanagawa.jp/",
    rateNum: 0.33,
    capManYen: 500,
  },
  {
    id: "osaka",
    name: "大阪府 中小事業者高効率空調機導入支援事業（R8）",
    org: "大阪府",
    period: "2026/4/13〜6/30（郵送必着・先着順）",
    rate: "1/2",
    max: "500万円（下限20万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["大阪府"],
    requirement: "脱炭素経営宣言登録事業者。府内事業所。高効率空調機",
    docs: "宣言登録証・事業計画書・見積書・カタログ",
    url: "https://www.pref.osaka.lg.jp/",
    rateNum: 0.5,
    capManYen: 500,
  },
];
