import { Subsidy } from "./types";

// 補助金データの確認日（注記・鮮度表示に使用）。データ更新時はここも更新。
export const SUBSIDY_DATA_ASOF = "2026年7月3日";

export const SUBSIDIES: Subsidy[] = [
  {
    id: "sii_iv",
    applyOpen: "2026-06-01",
    applyClose: "2026-07-09",
    scheduleNote: "2次公募 受付中（〜7/9）。3次は詳細決定次第SIIサイトで公表",
    name: "SII 省エネ・非化石転換補助金（設備単位型）",
    org: "一般社団法人 環境共創イニシアチブ（経済産業省）",
    period: "令和7年度補正：2次 2026/6/1〜7/9 受付中（1次終了・3次日程未定）",
    rate: "1/3以内",
    max: "1億円（事業全体）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "省エネルギー量の要件あり。指定設備（高効率空調等）導入。補助事業ポータル登録必須",
    docs: "事業計画書・見積書・省エネ計算書・設備カタログ・登記簿等",
    url: "https://syouenehojyokin.sii.or.jp/",
    rateNum: 0.33,
    capManYen: 10000,
  },
  {
    id: "sii_gx",
    applyOpen: "2026-06-01",
    applyClose: "2026-07-09",
    scheduleNote: "2次公募 受付中（〜7/9）。計3回予定・3次日程未定",
    name: "SII GX設備単位型（メーカー強化枠／トップ性能枠）",
    org: "一般社団法人 環境共創イニシアチブ",
    period: "令和7年度補正：2次 2026/6/1〜7/9 受付中／3次 日程未定",
    rate: "メーカー強化枠：上限3億円 / トップ性能枠：更新1/2・新設1/5",
    max: "3億円",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "省エネ要件 10%/1kl/1kl千万円のいずれか達成。トップランナー水準機器",
    docs: "SII事業計画書・型番リスト・省エネ計算書",
    url: "https://syouenehojyokin.sii.or.jp/",
    rateNum: 0.5,
    capManYen: 30000,
  },
  {
    id: "kanagawa",
    applyOpen: "2026-06-01",
    applyClose: "2026-11-30",
    scheduleNote: "先着順・予算到達で終了（前年度は10/10到達で早期終了。早めの申請推奨）",
    name: "神奈川県 中小企業省エネルギー設備導入費等補助金",
    org: "神奈川県",
    period: "2026/6/1〜11/30必着（先着順・予算到達で終了）",
    rate: "1/3",
    max: "500万円（再エネ認定で600万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["神奈川県"],
    requirement: "CO2削減量 3t/年以上。県内事業所。エアコン・LED・ボイラー等が対象",
    docs: "事業計画書・省エネ計算書・見積書・現況写真",
    url: "https://www.pref.kanagawa.jp/",
    rateNum: 0.33,
    capManYen: 500,
  },
  {
    id: "hotel_sustainability",
    scheduleNote: "令和7年度は終了（追加公募なし）。令和8年度公募は未発表・ウォッチ中",
    name: "宿泊施設サステナビリティ強化支援事業",
    org: "観光庁",
    period: "令和7年度 終了（追加公募なし）。令和8年度の公募は未発表",
    rate: "1/2",
    max: "1,000万円（1事業者あたり最大3施設）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "旅館業法の許可取得。高付加価値経営旅館等の登録（または申請中）。宿泊事業者と施工業者が同一会計でないこと。同一事業者で3施設以内。空調更新等が対象（採択率 約91%実績）",
    docs: "旅館業許可・図面/機器リスト・見積書・登録証・申請ポータル登録・実績報告書",
    url: "https://www.mlit.go.jp/kankocho/",
    rateNum: 0.5,
    capManYen: 1000,
  },
  {
    id: "osaka",
    applyOpen: "2026-04-13",
    applyClose: "2026-06-30",
    closed: true,
    scheduleNote: "2026/6/30で受付終了（2次募集なし）。申請1,201件に対し交付決定220件（7/2時点）",
    name: "大阪府 中小事業者高効率空調機導入支援事業（R8）",
    org: "大阪府",
    period: "2026/4/13〜6/30 受付終了（先着順・交付決定まで約4か月）",
    rate: "1/2",
    max: "500万円（下限20万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["大阪府"],
    requirement: "脱炭素経営宣言登録事業者。府内事業所。高効率空調機",
    docs: "宣言登録証・事業計画書・見積書・カタログ",
    url: "https://www.pref.osaka.lg.jp/",
    rateNum: 0.5,
    capManYen: 500,
  },
  {
    id: "jizokuka",
    applyOpen: "2026-11-05",
    applyClose: "2026-12-15",
    name: "小規模事業者持続化補助金（一般型・通常枠）",
    org: "全国商工会連合会 / 日本商工会議所（中小企業庁）",
    period: "令和8年度：受付 2026/11/5〜12/15（電子申請のみ・GビズIDプライム必須）",
    rate: "2/3（赤字賃上げは3/4）",
    max: "50万円（インボイス特例+50・賃上げ特例+150で最大250万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: "all",
    requirement: "小規模事業者のみ（商業・サービス業5人以下／製造業その他20人以下）。販路開拓・業務効率化の取組が対象で、商工会・商工会議所の支援を受け事業計画を作成。設備購入が補助対象経費に含まれるかは計画内容次第（単なる更新・修繕は対象外）。大企業・中堅は対象外。",
    docs: "経営計画書・補助事業計画書・事業支援計画書(様式4/商工会等発行)・GビズIDプライム・電子申請(Jグランツ)",
    url: "https://www.chusho.meti.go.jp/keiei/shokibo/jizoku/",
    rateNum: 0.667,
    capManYen: 50,
    infoOnly: true,
  },
];
