import { Subsidy } from "./types";

// 補助金データの確認日（注記・鮮度表示に使用）。データ更新時はここも更新。
export const SUBSIDY_DATA_ASOF = "2026年7月13日";

export const SUBSIDIES: Subsidy[] = [
  {
    id: "sii_iv",
    applyOpen: "2026-06-01",
    applyClose: "2026-07-09",
    scheduleNote: "2次公募 受付中（〜7/9）。3次は詳細決定次第SIIサイトで公表",
    name: "SII 省エネ・非化石転換補助金（設備単位型）",
    org: "一般社団法人 環境共創イニシアチブ（経済産業省）",
    period: "令和7年度補正：2次 2026/6/1〜7/9 受付中（1次終了・3次日程未定）",
    rate: "1/3以内",
    max: "1億円（事業全体）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "省エネルギー量の要件あり。指定設備（高効率空調等）導入。補助事業ポータル登録必須",
    docs: "事業計画書・見積書・省エネ計算書・設備カタログ・登記簿等",
    url: "https://syouenehojyokin.sii.or.jp/",
    rateNum: 0.33,
    capManYen: 10000,
    adoptionRate: "非公表（省エネ量・費用対効果で審査。要件充足で採択可能性）",
    difficulty: "高",
    difficultyNote: "省エネ計算書・事業計画・補助事業ポータル登録が必須。審査型で書類量が多い",
  },
  {
    id: "sii_gx",
    applyOpen: "2026-06-01",
    applyClose: "2026-07-09",
    scheduleNote: "2次公募 受付中（〜7/9）。計3回予定・3次日程未定",
    name: "SII GX設備単位型（メーカー強化枠／トップ性能枠）",
    org: "一般社団法人 環境共創イニシアチブ",
    period: "令和7年度補正：2次 2026/6/1〜7/9 受付中／3次 日程未定",
    rate: "メーカー強化枠：上限3億円 / トップ性能枠：更新1/2・新設1/5",
    max: "3億円",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "省エネ要件 10%/1kl/1kl千万円のいずれか達成。トップランナー水準機器",
    docs: "SII事業計画書・型番リスト・省エネ計算書",
    url: "https://syouenehojyokin.sii.or.jp/",
    rateNum: 0.5,
    capManYen: 30000,
    adoptionRate: "非公表（トップランナー水準機器で要件充足が前提）",
    difficulty: "高",
    difficultyNote: "トップランナー水準機器＋省エネ要件(10%/1kl等)の立証が必要",
  },
  {
    id: "kanagawa",
    applyOpen: "2026-06-01",
    applyClose: "2026-11-30",
    scheduleNote: "先着順・予算到達で終了（前年度は10/10到達で早期終了。早めの申請推奨）",
    name: "神奈川県 中小企業省エネルギー設備導入費等補助金",
    org: "神奈川県",
    period: "2026/6/1〜11/30必着（先着順・予算到達で終了）",
    rate: "1/3",
    max: "500万円（再エネ認定で600万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["神奈川県"],
    requirement: "CO2削減量 3t/年以上。県内事業所。エアコン・LED・ボイラー等が対象",
    docs: "事業計画書・省エネ計算書・見積書・現況写真",
    url: "https://www.pref.kanagawa.jp/",
    rateNum: 0.33,
    capManYen: 500,
    adoptionRate: "先着順・予算枠方式（要件充足かつ枠内なら採択。前年度は早期終了）",
    difficulty: "中",
    difficultyNote: "CO2削減計算と見積が必要だが自治体先着型で審査は比較的シンプル。早期の枠確保がカギ",
  },
  {
    id: "hotel_sustainability",
    scheduleNote: "令和7年度は終了（追加公募なし）。令和8年度公募は未発表・ウォッチ中",
    name: "宿泊施設サステナビリティ強化支援事業",
    org: "観光庁",
    period: "令和7年度 終了（追加公募なし）。令和8年度の公募は未発表",
    rate: "1/2",
    max: "1,000万円（1事業者あたり最大3施設）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme", "middle", "large"],
    pref: "all",
    requirement: "旅館業法の許可取得。高付加価値経営旅館等の登録（または申請中）。宿泊事業者と施工業者が同一会計でないこと。同一事業者で3施設以内。空調更新等が対象（採択率 約91%実績）",
    docs: "旅館業許可・図面/機器リスト・見積書・登録証・申請ポータル登録・実績報告書",
    url: "https://www.mlit.go.jp/kankocho/",
    rateNum: 0.5,
    capManYen: 1000,
    adoptionRate: "約91%（令和7年度実績・要件充足前提）",
    difficulty: "中",
    difficultyNote: "旅館業許可・高付加価値経営旅館の登録が前提だが、採択率が高く要件を満たせば通りやすい",
  },
  {
    id: "osaka",
    applyOpen: "2026-04-13",
    applyClose: "2026-06-30",
    closed: true,
    scheduleNote: "2026/6/30で受付終了（2次募集なし）。申請1,201件に対し交付決定220件（7/2時点）",
    name: "大阪府 中小事業者高効率空調機導入支援事業（R8）",
    org: "大阪府",
    period: "2026/4/13〜6/30 受付終了（先着順・交付決定まで約4か月）",
    rate: "1/2",
    max: "500万円（下限20万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["大阪府"],
    requirement: "脱炭素経営宣言登録事業者。府内事業所。高効率空調機",
    docs: "宣言登録証・事業計画書・見積書・カタログ",
    url: "https://www.pref.osaka.lg.jp/",
    rateNum: 0.5,
    capManYen: 500,
    adoptionRate: "先着順・予算枠方式（R8は申請1,201件→交付決定220件・7/2時点）",
    difficulty: "中",
    difficultyNote: "脱炭素経営宣言の登録＋書類。先着型で審査自体は要件確認中心",
  },
  {
    id: "tokyo_zeroemi",
    applyOpen: "2026-04-21",
    scheduleNote: "令和8年度は年6回程度の受付（第1回 4/21〜5/8 実施済み）。次回回次はクール・ネット東京で公表。予算枠あり・早めの申請推奨",
    name: "東京都 ゼロエミッション化に向けた省エネ設備導入・運用改善支援事業",
    org: "東京都地球温暖化防止活動推進センター（クール・ネット東京）",
    period: "令和8年度：年6回程度の受付回で公募（高効率空調・変圧器・LED等）",
    rate: "2/3（区分により上限変動）",
    max: "最大2,500万円（省エネ診断・自己作成プラン等の区分による）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["東京都"],
    requirement: "都内の中小規模事業所。高効率空調等の指定省エネ設備。省エネ診断の受診または自己作成の省エネ計画。CO2/エネルギー削減の要件あり",
    docs: "交付申請書・省エネ診断書または省エネ計画・見積書・設備仕様書・現況写真",
    url: "https://www.tokyo-co2down.jp/subsidy/zeroemi-shoene/",
    rateNum: 0.667,
    capManYen: 2500,
    adoptionRate: "予算枠方式（要件充足で交付。回次ごとの予算枠あり・早めの申請推奨）",
    difficulty: "中",
    difficultyNote: "省エネ診断の受診または自己作成の省エネ計画が必要。補助率2/3と高い分、書類はやや多め",
  },
  {
    id: "saitama",
    applyOpen: "2026-04-27",
    scheduleNote: "令和8年度は4/27から先着受付予定。予算到達で終了（早めの申請推奨）",
    name: "埼玉県 企業等における省エネ・再エネ活用設備導入補助金",
    org: "埼玉県",
    period: "令和8年度：2026/4/27〜 先着順（予算到達で終了）",
    rate: "1/2",
    max: "1,000万円",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["埼玉県"],
    requirement: "県内の事業所。高効率空調（エアコン）・変圧器・EMS等の省エネ設備。CO2削減見込みの要件あり",
    docs: "交付申請書・事業計画・省エネ計算書・見積書・現況写真",
    url: "https://www.pref.saitama.lg.jp/a0503/datutanso.html",
    rateNum: 0.5,
    capManYen: 1000,
    adoptionRate: "先着順・予算枠方式（予算到達で終了。早めの申請推奨）",
    difficulty: "中",
    difficultyNote: "先着型・省エネ計算書と見積が中心。早期の枠確保がカギ",
  },
  {
    id: "chiba",
    applyClose: "2026-10-07",
    scheduleNote: "令和8年度：設備導入は10/7締切（診断のみは12/11）。実績報告は令和9年1/29まで",
    name: "千葉県 業務用設備等脱炭素化促進事業補助金",
    org: "千葉県",
    period: "令和8年度：設備導入 交付申請〜2026/10/7（省エネ診断あり）",
    rate: "1/2（省エネ診断あり）／1/4（簡易自己診断）",
    max: "1,000万円（省エネ診断あり）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: ["千葉県"],
    requirement: "県内の中小事業者等。省エネルギー診断の受診（または簡易自己診断）に基づく高効率空調等の脱炭素設備導入。CO2削減見込みに応じて対象",
    docs: "交付申請書・省エネ診断報告書・見積書・設備仕様書・現況写真",
    url: "https://www.pref.chiba.lg.jp/ontai/hojo/r8jigyousyahojo.html",
    rateNum: 0.5,
    capManYen: 1000,
    adoptionRate: "予算枠方式（省エネ診断に基づく要件充足で交付。締切10/7）",
    difficulty: "高",
    difficultyNote: "省エネ診断の受診が前提（補助率1/2）。簡易自己診断なら手間は減るが補助率1/4に低下",
  },
  {
    id: "jizokuka",
    applyOpen: "2026-11-05",
    applyClose: "2026-12-15",
    name: "小規模事業者持続化補助金（一般型・通常枠）",
    org: "全国商工会連合会 / 日本商工会議所（中小企業庁）",
    period: "令和8年度：受付 2026/11/5〜12/15（電子申請のみ・GビズIDプライム必須）",
    rate: "2/3（赤字賃上げは3/4）",
    max: "50万円（インボイス特例+50・賃上げ特例+150で最大250万円）",
    target: ["ac", "multi"],
    biz: ["business"],
    size: ["sme"],
    pref: "all",
    requirement: "小規模事業者のみ（商業・サービス業5人以下／製造業その他20人以下）。販路開拓・業務効率化の取組が対象で、商工会・商工会議所の支援を受け事業計画を作成。設備購入が補助対象経費に含まれるかは計画内容次第（単なる更新・修繕は対象外）。大企業・中堅は対象外。",
    docs: "経営計画書・補助事業計画書・事業支援計画書(様式4/商工会等発行)・GビズIDプライム・電子申請(Jグランツ)",
    url: "https://www.chusho.meti.go.jp/keiei/shokibo/jizoku/",
    rateNum: 0.667,
    capManYen: 50,
    infoOnly: true,
    adoptionRate: "約48%（第18回 48.1%／通常枠・年度回次で変動）",
    difficulty: "中",
    difficultyNote: "商工会・商工会議所の支援を受け経営計画を作成。GビズID・電子申請。空調単純更新は対象外の点に注意",
  },
];
